service: esg-rating-getter

provider:
  name: aws
  runtime: python3.7

functions:
  get_esg_rating:
    handler: handler.get_esg_rating

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - __pycache__/**
    - node_modules/**